version: '3'

services:
  web:
    image: robertfreeman/builddemo
    ports:
      - "80:8000"
    networks:
      - counter-backend

  redis:
    image: redis:alpine
    networks:
      - counter-backend

    environment:
        SERVICE_NAME: buildweb

networks:
    counter-backend:
