on:
  push:
    branches:
    - master
name: Build and Push
jobs:
  dockerbuild2:
    name: Docker Build
    runs-on: ubuntu-latest
    steps:
    - uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: robertefreeman/builddemo
        tags: latest
        tag_with_ref: true
        tag_with_sha: true
#  dockerBuild:
#    name: Docker Build
#    runs-on: ubuntu-latest
#    steps:
#    - uses: actions/checkout@master
#    - name: Docker Build
#      uses: actions/docker/cli@86ab5e854a74b50b7ed798a94d9b8ce175d8ba19
#      with:
#        args: build -t robertfreeman/builddemo .
#    - name: Docker Login
#      uses: actions/docker/login@86ab5e854a74b50b7ed798a94d9b8ce175d8ba19
#      env:
#        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
#        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
#    - name: Docker Push
#      uses: actions/docker/cli@86ab5e854a74b50b7ed798a94d9b8ce175d8ba19
#      with:
#        args: push robertfreeman/builddemo
