on:
  push:
    branches:
    - master
name: Build and Push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: robertfreeman/builddemo
        tags: latest
        tag_with_ref: true
        tag_with_sha: true

    - uses: azure/aks-set-context@v1
      with:
        creds: '${{ secrets.AZURE_CRED }}' # Azure credentials
        resourceGroupName: girhub-demos
        clusterName: r0bk8s
        
    - uses: Azure/k8s-deploy@v1
      with:
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          docker.io/library/nginxdemos/hello
        
#  dockerBuild:
#    name: Docker Build
#    runs-on: ubuntu-latest
#    steps:
#    - uses: actions/checkout@master
#    - name: Docker Build
#      uses: actions/docker/cli@86ab5e854a74b50b7ed798a94d9b8ce175d8ba19
#      with:
#        args: build -t robertfreeman/builddemo .
#    - name: Docker Login
#      uses: actions/docker/login@86ab5e854a74b50b7ed798a94d9b8ce175d8ba19
#      env:
#        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
#        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
#    - name: Docker Push
#      uses: actions/docker/cli@86ab5e854a74b50b7ed798a94d9b8ce175d8ba19
#      with:
#        args: push robertfreeman/builddemo
